export const REFUND = {
    REQUEST_REFUND: 'REQUEST REFUND',
    REFUND_APPROVED: 'REFUND APPROVED',
    REFUND_CANCELLED: 'REFUND CANCELLED'
};

export const BOOKING_STATUS = {
    TICKETED: 'TICKETED',
    BOOKED: 'BOOKED',
    REQUEST_REFUND: 'REQUEST REFUND',
    REFUND_APPROVED: 'REFUND APPROVED',
    REFUND_CANCELLED: 'REFUND CANCELLED'
};
export const USER_ID_FOR_CLIENT_PAID_BY_ADMIN_DASHBOARD =
    '84d4f79a-3bc8-4713-a0bd-45f20678abcc';
