# agent/router.py  — latest-LangGraph-native supervisor (no langgraph_supervisor)
from __future__ import annotations

import json
from functools import partial
from typing import TypedDict, Literal, Optional, List, cast

from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage, BaseMessage

from agent.performance import (
    timer,
    optimize_messages,
    extract_context_early,
    cache_key_for_decision,
    get_cached_decision,
    cache_decision,
)
from langgraph.graph import StateGraph, END
from langgraph.types import Command
from langgraph.graph.message import add_messages  # reducer for chat histories

# === bring your compiled worker graphs ===
from agent.agent import graph as umoja_graph
from agent.company_information.conversation_workflow import graph as conversation_graph
from agent.update_journey.update_journey_workflow import graph as update_journey_graph
from agent.synthesizer import WorkerResult, synthesizer_node
from agent.travel_provider import ACTIVE_TRAVEL_PROVIDER_LABEL, active_travel_graph

from dotenv import load_dotenv
load_dotenv()
import os
# ---------- LLM ----------
model = os.getenv("GROQ_MODEL", "openai/gpt-oss-safeguard-20b")
llm = ChatGroq(model=model)  # adjust default as needed

# -----------------------------
# State
# -----------------------------
class OrchestratorState(TypedDict, total=False):
    messages: list[BaseMessage]
    # set once on the first turn where the model provides it
    title: Optional[str]
    # routing results from the orchestrator's JSON
    route: Optional[
        Literal["Umoja_Workflow", "Amadeus_Workflow", "Conversation_Workflow", "Update_Journey_Workflow", "direct"]
    ]
    # if present, we will forward the last worker message verbatim to the user
    forward_from_agent: Optional[
        Literal["Umoja_Workflow", "Amadeus_Workflow", "Conversation_Workflow", "Update_Journey_Workflow"]
    ]
    # synthesized worker outputs captured after each worker finishes
    worker_results: List[WorkerResult]
    # message index snapshot taken right before a worker starts
    worker_cursor: int
    # queue of remaining routes for multi-task execution
    route_queue: Optional[List[str]]
    # identified tasks for multi-task scenarios
    tasks_identified: Optional[List[str]]
    # shared context that flows between tasks (e.g., flight details → car/hotel)
    task_context: Optional[dict]
    # accumulated results from all completed tasks
    accumulated_results: Optional[List[WorkerResult]]


# messages reducer (LangGraph built-in for chat histories)
MessagesState = {"messages": add_messages}


# -----------------------------
# Prompt & schema
# -----------------------------
ORCH_INSTRUCTIONS = """
You are the Umoja AI Orchestrator overseeing three supervisor-led graphs: {members}.
Your mission is to route each user turn to the best supervisor while keeping the conversation coherent.

Supervisors:
- Umoja_Workflow: Umoja-operated travel services (luggage, check-in, in-house recommendations).
- Amadeus_Workflow: Global travel services route backed by the active provider ({active_travel_provider}) for flights, hotels, cars, and reservation flows.
- Update_Journey_Workflow: All journey-related requests — planning a new trip, managing an existing journey, viewing journey details, updating destination/dates/budget/travelers, transitioning journey phases, managing saved flights, archiving or cancelling a journey. This is the single entry point for anything journey-related.
- Conversation_Workflow: greetings, small talk, Umoja/NDIT knowledge (Mongo/SQL tools), generic Q&A.

ENHANCED CAPABILITIES:
- Contextual Disambiguation: Resolve pronouns using conversation history
  * "Book it" → Knows "it" = Flight 3 from previous search
  * "What about hotels?" → Knows destination from booked flight
- Implicit Intent Detection: Infer actions from statements
  * "I'm at the airport" → Triggers location check + segment transition
  * "Running late" → Checks traffic + recalculates timeline
- Alternative Planning: Suggest backup options for high-risk situations
  * High delay risk → Suggest earlier flights
  * Hotel fully booked → Queue alternatives
- Safety Alerts: Warn about travel advisories, disasters, health alerts

MULTILINGUAL INSTRUCTION:
- The conversation may include a system hint such as `speech_locale=<locale>` or other language context.
- You may reason internally in English if that helps with routing and task decomposition.
- However, when the final user-facing response is generated by downstream workers, it must be in the user's input language whenever a non-English language is indicated by context.
- Do not ask the user to switch to English unless absolutely necessary.
- Do not mention that you translated internally unless the user explicitly asks.

CRITICAL ROUTING OVERRIDE (JOURNEY DASHBOARD):
If the system message indicates "The user is messaging from the specific Journey Dashboard page for this journey", route general journey discussion, timeline inquiries, segment transitions, status checks, and journey updates to "Update_Journey_Workflow". HOWEVER, if the user explicitly asks to search for, compare, book, or SAVE flights, hotels, or rental cars, you MUST route that intent to "Amadeus_Workflow" (or use multi-task routing if they ask for multiple).

JOURNEY RESOLUTION FLOW (when no journey_id is provided):
When a user references a journey by description (e.g. "my Dubai trip", "the journey I had last month") but NO journey_id is present in context, ALWAYS route to "Update_Journey_Workflow" — do NOT ask the user for the ID yourself. The agent will:
1. Fetch all journeys for the user and attempt to match by destination, dates, or name.
2. If still ambiguous after filtering, ask the user for ONE clarifying detail only (e.g. "Was this the trip in March or June?").
3. If no match is found after that one follow-up, offer to create a new journey for the user instead.
The orchestrator must NEVER block on a missing journey_id — always forward to "Update_Journey_Workflow" and let it resolve.

JOURNEY_ID BEFORE BOOKING (CRITICAL):
When the user's intent is to BOOK or RESERVE a flight (not just search or compare), a journey_id must be in context
so the booking agent can save the confirmed booking to the journey automatically.

- If a journey_id IS already present in the conversation context (system message contains journey_id):
  → Route directly to "Amadeus_Workflow". No pre-step needed.

- If NO journey_id is in context and the intent is to BOOK a flight:
  → Use multi-task: ["Update_Journey_Workflow", "Amadeus_Workflow"]
  → tasks_identified: ["resolve or create journey to get journey_id", "book flight"]
  → Update_Journey_Workflow runs first, resolves/creates the journey, and puts the journey_id into context.
  → Amadeus_Workflow then proceeds with the booking and the journey_id is already available.

- If the intent is only to SEARCH or COMPARE flights (not book):
  → Route directly to "Amadeus_Workflow". Journey resolution is not required for searches.

CRITICAL MULTI-TASK DETECTION PATTERNS:
1. BOOK FLIGHT (no journey_id in context): ["Update_Journey_Workflow", "Amadeus_Workflow"]
2. FLIGHT + HOTEL: "fly to X and stay at Y" → ["Amadeus_Workflow", "Amadeus_Workflow"]
3. FLIGHT + CAR: "fly to X and rent a car" → ["Amadeus_Workflow", "Amadeus_Workflow"]
4. FLIGHT + CAR + HOTEL: "fly to X, rent car, need hotel" → ["Amadeus_Workflow", "Amadeus_Workflow", "Amadeus_Workflow"]
5. HOTEL + CAR ONLY: "I need hotel and car in Paris" → ["Amadeus_Workflow", "Amadeus_Workflow"]
6. SINGLE SEARCH: "find flights to Paris" → "target": "Amadeus_Workflow" (NOT array)

DEPENDENCY ORDER (CRITICAL):
- If journey resolution needed: Update_Journey_Workflow FIRST → then Amadeus_Workflow
- If multi-service: ALWAYS put flights FIRST — flight info (destination, dates) needed by cars/hotels
- Example: ["Update_Journey_Workflow", "Amadeus_Workflow"(flights), "Amadeus_Workflow"(hotels)]

MULTI-TASK EXECUTION:
- Tasks execute SEQUENTIALLY (not parallel)
- First task completes → context extracted → second task starts with context → etc.
- Context flows automatically: journey_id → used by booking agent; flight destination/dates → used by car/hotel searches

Rules:
1) DECOMPOSE: Parse user message to identify ALL distinct tasks
2) CHECK: Is intent to BOOK a flight? Is journey_id in context? If booking and no journey_id → prepend Update_Journey_Workflow
3) COUNT: How many separate services requested? (flights=1, cars=1, hotels=1, etc.)
4) ROUTE MULTIPLE: If count >= 2, return "targets" ARRAY
5) ROUTE SINGLE: If count = 1, return "target" STRING (not array)
6) IDENTIFY: Set "tasks_identified" array with clear task descriptions
7) RATIONALE: Explain your task decomposition briefly
8) If missing info, ask question but still route to most likely workflow
9) If none apply, answer directly ("direct")

EXAMPLES:
User: "Book this flight to Paris" (no journey_id in context)
→ {{"targets": ["Update_Journey_Workflow", "Amadeus_Workflow"], "tasks_identified": ["resolve or create journey to get journey_id", "book flight to Paris"], "rationale": "Booking intent with no journey_id — resolve journey first so booking agent can save the confirmed flight"}}

User: "Book this flight to Paris" (journey_id already in context)
→ {{"target": "Amadeus_Workflow", "rationale": "Booking intent; journey_id already in context — booking agent will save confirmed flight to journey"}}

User: "Book flight to Paris and find hotel" (no journey_id in context)
→ {{"targets": ["Update_Journey_Workflow", "Amadeus_Workflow", "Amadeus_Workflow"], "tasks_identified": ["resolve or create journey", "book flight", "find hotel"], "rationale": "Booking + hotel; resolve journey first for booking agent"}}

User: "Find me flights to London"
→ {{"target": "Amadeus_Workflow", "rationale": "Search only (no booking intent) — no journey resolution needed"}}

User: "I need luggage assistance on my Umoja flight"
→ {{"target": "Umoja_Workflow", "rationale": "Single task: Umoja luggage service"}}

User: "I had a journey to Dubai, can you update the dates?"
→ {{"target": "Update_Journey_Workflow", "rationale": "Journey update requested; no journey_id provided — agent will resolve via user's journey list"}}

User: "Update my trip to Paris"
→ {{"target": "Update_Journey_Workflow", "rationale": "Journey update requested; no journey_id — agent will fetch all journeys and match by destination"}}
"""

SCHEMA_HINT_BASE = """
Return one JSON object ONLY, matching:

type OrchestratorDecision = {
  "target"?: "Umoja_Workflow" | "Amadeus_Workflow" | "Conversation_Workflow" | "Update_Journey_Workflow" | "direct",
  "targets"?: Array<"Umoja_Workflow" | "Amadeus_Workflow" | "Conversation_Workflow" | "Update_Journey_Workflow">,
  "rationale": string,
  "direct_reply"?: string,
  "forward_from_agent"?: "Umoja_Workflow" | "Amadeus_Workflow" | "Conversation_Workflow" | "Update_Journey_Workflow",
  "missing_info_question"?: string,
  "title"?: string,
  "tasks_identified"?: Array<string>,
  "task_instructions"?: string
}

MULTI-TASK ROUTING RULES:
- Single task: Use "target" (string). Example: "target": "Amadeus_Workflow"
- Multiple tasks: Use "targets" (array). Example: "targets": ["Amadeus_Workflow", "Amadeus_Workflow", "Amadeus_Workflow"]
- For multiple tasks, ALSO provide "tasks_identified": ["search flights", "book car", "find hotel"]
- Optionally add "task_instructions": brief context for the workflow to understand what to do
- Tasks execute SEQUENTIALLY in array order. Put flights before cars/hotels.
- If more input is needed, set "missing_info_question" and choose the most likely "target".
- If answering directly, set "target":"direct" and include "direct_reply".
- If forwarding worker text verbatim, set "forward_from_agent".
- Output JSON ONLY (no markdown, no prose).
"""

MAX_TOKENS = 4000  # ~16k chars, safer token limit for context


def _trim_messages(messages: List[BaseMessage], max_tokens: int = MAX_TOKENS) -> List[BaseMessage]:
    """Optimize message history using intelligent trimming"""
    if not messages:
        return messages

    # Use performance-optimized message trimming
    with timer("message_optimization"):
        optimized = optimize_messages(
            messages,
            max_tokens=max_tokens,
            keep_system=True,
            keep_recent_human=3,  # Keep last 3 user messages for context
        )

    return optimized


def _has_title(messages: List[BaseMessage]) -> bool:
    # heuristic: if any past AI message contains "title" in JSON, assume it’s set
    for m in messages:
        if isinstance(m, AIMessage) and '"title"' in str(getattr(m, "content", "")):
            return True
    return False


def _orchestrator_decide(messages: List[BaseMessage], thread_has_title: bool) -> dict:
    """Run the LLM once to get JSON routing with performance optimizations"""

    # Check cache first (simple caching for repeated similar requests)
    cache_key = cache_key_for_decision(messages)
    cached = get_cached_decision(cache_key)
    if cached and not thread_has_title:  # Don't use cache for first message (need title)
        return cached

    schema_directive = SCHEMA_HINT_BASE + (
        "\nTitle directive: This is the FIRST decision; you MUST include 'title'."
        if not thread_has_title else
        "\nTitle directive: This thread already has a title; DO NOT include 'title'."
    )

    sys = SystemMessage(content=ORCH_INSTRUCTIONS.format(
        members="Umoja_Workflow, Amadeus_Workflow, Conversation_Workflow, Update_Journey_Workflow",
        active_travel_provider=ACTIVE_TRAVEL_PROVIDER_LABEL,
    ))
    schema = SystemMessage(content=schema_directive)

    # Optimize message history before LLM call
    with timer("message_trimming"):
        trimmed = _trim_messages(messages)

    # Invoke LLM with timing
    with timer("orchestrator_llm_decision"):
        out = llm.invoke([sys, schema] + trimmed)

    text = getattr(out, "content", "").strip()

    # Parse response with timing
    with timer("json_parsing"):
        try:
            data = json.loads(text)
            if not isinstance(data, dict):
                raise ValueError("Model did not return an object")
        except Exception:
            # fallback: minimal direct reply
            return {
                "target": "direct",
                "rationale": "LLM returned non-JSON; responding directly.",
                "direct_reply": text or "Sorry, I couldn't parse the decision."
            }

    # Cache the decision (except for first message with title)
    if not thread_has_title:
        cache_decision(cache_key, data)

    return data


# -----------------------------
# Orchestrator node
# -----------------------------
def orchestrator_node(state: OrchestratorState) -> OrchestratorState | Command[OrchestratorState]:
    messages = state.get("messages", [])

    # Check if we're resuming from a queue (multi-task continuation)
    route_queue = state.get("route_queue", [])
    if route_queue:
        # Pop next task from queue
        target = route_queue.pop(0)
        if route_queue:
            state["route_queue"] = route_queue
        else:
            state.pop("route_queue", None)

        # Continue with queued task without re-deciding
        state["route"] = cast(OrchestratorState["route"], target)
        state["worker_cursor"] = len(state.get("messages", []))
        state.setdefault("worker_results", [])

        # Add context hint for this task if available
        tasks = state.get("tasks_identified", [])
        task_idx = len(state.get("accumulated_results", [])) if state.get("accumulated_results") else 0
        if task_idx < len(tasks):
            task_hint = f"[TASK {task_idx + 1}/{len(tasks)}]: {tasks[task_idx]}"
            # Prepend task context as a system message
            task_msg = SystemMessage(content=task_hint)

            # Extract context early if not already present (performance optimization)
            if not state.get("task_context"):
                with timer("early_context_extraction"):
                    extracted = extract_context_early(messages)
                    if extracted:
                        state["task_context"] = extracted

            if state.get("task_context"):
                task_msg.content += f"\nContext from previous tasks: {json.dumps(state['task_context'])}"
            state["messages"] = messages + [task_msg]

        return Command(goto=target, update=state)

    # New decision needed
    decision = _orchestrator_decide(messages, thread_has_title=bool(state.get("title")))

    # Support either a single `target` or a sequence via `targets`.
    raw_targets = decision.get("targets") or decision.get("target")
    if isinstance(raw_targets, list):
        targets = [str(t) for t in raw_targets]
    elif isinstance(raw_targets, str) and "," in raw_targets:
        targets = [t.strip() for t in raw_targets.split(",") if t.strip()]
    else:
        targets = [raw_targets] if raw_targets is not None else ["direct"]

    target = cast(str, targets[0] if targets else "direct")
    rationale = decision.get("rationale", "")

    # store title once if provided and not yet set
    if "title" in decision and not state.get("title"):
        state["title"] = decision["title"]

    # Store identified tasks for multi-task scenarios
    if "tasks_identified" in decision:
        state["tasks_identified"] = decision["tasks_identified"]

    # Initialize accumulated results for multi-task
    if len(targets) > 1:
        state.setdefault("accumulated_results", [])
        state.setdefault("task_context", {})

    # if the model wants to ask a missing-info question, append it and still route
    if q := decision.get("missing_info_question"):
        state["messages"] = messages + [AIMessage(content=q)]

    # forward setting (handled after worker finishes; see orchestrator_return)
    if "forward_from_agent" in decision:
        state["forward_from_agent"] = decision["forward_from_agent"]

    # direct reply path
    if target == "direct":
        reply = decision.get("direct_reply") or "(no reply provided)"
        state["messages"] = messages + [AIMessage(content=reply)]
        return state  # end

    # set the route and jump to that worker node
    state["route"] = cast(OrchestratorState["route"], target)
    state["worker_cursor"] = len(state.get("messages", []))
    state.setdefault("worker_results", [])
    # if multiple targets provided, store the remainder as a queue
    if len(targets) > 1:
        state["route_queue"] = targets[1:]
        # Add task hint for first task
        tasks = state.get("tasks_identified", [])
        if tasks:
            task_hint = f"[TASK 1/{len(targets)}]: {tasks[0]}"
            state["messages"] = messages + [SystemMessage(content=task_hint)]

    return Command(goto=target, update=state)


# -----------------------------
# Graph wiring
# -----------------------------
graph_builder = StateGraph(OrchestratorState)

# nodes:
graph_builder.add_node("orchestrator", orchestrator_node)
graph_builder.add_node("Umoja_Workflow", umoja_graph)
graph_builder.add_node("Amadeus_Workflow", active_travel_graph)
graph_builder.add_node("Conversation_Workflow", conversation_graph)
graph_builder.add_node("Update_Journey_Workflow", update_journey_graph)
graph_builder.add_node("synthesizer", partial(synthesizer_node, llm=llm))

# entrypoint
graph_builder.set_entry_point("orchestrator")


def route_orchestrator(state: OrchestratorState) -> str:
    return state.get("route") or "direct"


graph_builder.add_conditional_edges(
    "orchestrator",
    route_orchestrator,
    {
        "Umoja_Workflow": "Umoja_Workflow",
        "Amadeus_Workflow": "Amadeus_Workflow",
        "Conversation_Workflow": "Conversation_Workflow",
        "Update_Journey_Workflow": "Update_Journey_Workflow",
        "direct": END,
    },
)

# after any worker, return to synthesizer then end
for worker in ("Umoja_Workflow", "Amadeus_Workflow", "Conversation_Workflow", "Update_Journey_Workflow"):
    graph_builder.add_edge(worker, "synthesizer")

def _decide_synth_return(state: OrchestratorState) -> str:
    # If there's a queued route from the orchestrator, continue to orchestrator
    if state.get("route_queue"):
        return "orchestrator"
    return "end"

graph_builder.add_conditional_edges(
    "synthesizer",
    _decide_synth_return,
    {
        "orchestrator": "orchestrator",
        "end": END,
    },
)

graph = graph_builder.compile(name="Orchestrator_Workflow")
