/**
 * IATA airport code → city name mapping.
 * Used for displaying human-readable route labels.
 */
const AIRPORT_CITY_MAP: Record<string, string> = {
  // Africa
  ADD: "Addis Ababa",
  ALG: "Algiers",
  ACC: "Accra",
  ABJ: "Abidjan",
  CAI: "Cairo",
  CPT: "Cape Town",
  CMN: "Casablanca",
  DAR: "Dar es Salaam",
  DSS: "Dakar",
  DUR: "Durban",
  EBB: "Entebbe",
  JNB: "Johannesburg",
  KGL: "Kigali",
  LOS: "Lagos",
  LAD: "Luanda",
  MBA: "Mombasa",
  MPM: "Maputo",
  NBO: "Nairobi",
  RAK: "Marrakech",
  RUN: "Réunion",
  SSH: "Sharm El Sheikh",
  TUN: "Tunis",
  WDH: "Windhoek",
  ZNZ: "Zanzibar",

  // Asia
  AMD: "Ahmedabad",
  AUH: "Abu Dhabi",
  BAH: "Bahrain",
  BKK: "Bangkok",
  BLR: "Bengaluru",
  BOM: "Mumbai",
  CCU: "Kolkata",
  CEB: "Cebu",
  CGK: "Jakarta",
  CKG: "Chongqing",
  CMB: "Colombo",
  CNX: "Chiang Mai",
  CTS: "Sapporo",
  CTU: "Chengdu",
  DAD: "Da Nang",
  DEL: "Delhi",
  DPS: "Bali",
  DOH: "Doha",
  DXB: "Dubai",
  FUK: "Fukuoka",
  GAN: "Gan Island",
  GOI: "Goa",
  HAN: "Hanoi",
  HGH: "Hangzhou",
  HKG: "Hong Kong",
  HKT: "Phuket",
  HND: "Tokyo Haneda",
  HYD: "Hyderabad",
  ICN: "Seoul Incheon",
  ISB: "Islamabad",
  JED: "Jeddah",
  KHI: "Karachi",
  KIX: "Osaka Kansai",
  KTM: "Kathmandu",
  KUL: "Kuala Lumpur",
  KWI: "Kuwait City",
  LHE: "Lahore",
  MAA: "Chennai",
  MCT: "Muscat",
  MFM: "Macau",
  MLE: "Malé",
  MNL: "Manila",
  NRT: "Tokyo Narita",
  PBH: "Paro",
  PEK: "Beijing Capital",
  PKX: "Beijing Daxing",
  PNH: "Phnom Penh",
  PVG: "Shanghai Pudong",
  REP: "Siem Reap",
  RGN: "Yangon",
  RUH: "Riyadh",
  SGN: "Ho Chi Minh City",
  SHA: "Shanghai Hongqiao",
  SIN: "Singapore",
  SZX: "Shenzhen",
  TLV: "Tel Aviv",
  TPE: "Taipei",
  ULN: "Ulaanbaatar",
  VTE: "Vientiane",
  XIY: "Xi'an",

  // Europe
  AMS: "Amsterdam",
  ARN: "Stockholm",
  ATH: "Athens",
  BCN: "Barcelona",
  BEG: "Belgrade",
  BER: "Berlin",
  BRU: "Brussels",
  BTS: "Bratislava",
  BUD: "Budapest",
  CDG: "Paris CDG",
  CIA: "Rome Ciampino",
  CPH: "Copenhagen",
  DUB: "Dublin",
  DUS: "Düsseldorf",
  EDI: "Edinburgh",
  EVN: "Yerevan",
  FCO: "Rome Fiumicino",
  FRA: "Frankfurt",
  GVA: "Geneva",
  HAM: "Hamburg",
  HEL: "Helsinki",
  IST: "Istanbul",
  KBP: "Kyiv",
  LCA: "Larnaca",
  LED: "St. Petersburg",
  LGW: "London Gatwick",
  LHR: "London Heathrow",
  LIS: "Lisbon",
  LTN: "London Luton",
  LUX: "Luxembourg",
  MAD: "Madrid",
  MAN: "Manchester",
  MLA: "Malta",
  MUC: "Munich",
  MXP: "Milan Malpensa",
  NAP: "Naples",
  NCE: "Nice",
  OPO: "Porto",
  ORY: "Paris Orly",
  OSL: "Oslo",
  OTP: "Bucharest",
  PMI: "Palma de Mallorca",
  PRG: "Prague",
  RIX: "Riga",
  SAW: "Istanbul Sabiha",
  SOF: "Sofia",
  STN: "London Stansted",
  SVO: "Moscow Sheremetyevo",
  TBS: "Tbilisi",
  TLL: "Tallinn",
  VCE: "Venice",
  VIE: "Vienna",
  VNO: "Vilnius",
  WAW: "Warsaw",
  ZAG: "Zagreb",
  ZRH: "Zurich",

  // North America
  ATL: "Atlanta",
  AUS: "Austin",
  BNA: "Nashville",
  BOS: "Boston",
  BWI: "Baltimore",
  CLE: "Cleveland",
  CLT: "Charlotte",
  CUN: "Cancún",
  CVG: "Cincinnati",
  DCA: "Washington Reagan",
  DEN: "Denver",
  DFW: "Dallas",
  DTW: "Detroit",
  EWR: "Newark",
  FLL: "Fort Lauderdale",
  GDL: "Guadalajara",
  HAV: "Havana",
  HNL: "Honolulu",
  IAD: "Washington Dulles",
  IAH: "Houston",
  IND: "Indianapolis",
  JFK: "New York JFK",
  KIN: "Kingston",
  LAS: "Las Vegas",
  LAX: "Los Angeles",
  LGA: "New York LaGuardia",
  MBJ: "Montego Bay",
  MCI: "Kansas City",
  MCO: "Orlando",
  MEX: "Mexico City",
  MIA: "Miami",
  MKE: "Milwaukee",
  MSP: "Minneapolis",
  MSY: "New Orleans",
  MTY: "Monterrey",
  OAK: "Oakland",
  ORD: "Chicago O'Hare",
  PBI: "West Palm Beach",
  PDX: "Portland",
  PHL: "Philadelphia",
  PHX: "Phoenix",
  PIT: "Pittsburgh",
  POS: "Port of Spain",
  PTY: "Panama City",
  PUJ: "Punta Cana",
  PVR: "Puerto Vallarta",
  RDU: "Raleigh",
  RSW: "Fort Myers",
  SAN: "San Diego",
  SAT: "San Antonio",
  SEA: "Seattle",
  SFO: "San Francisco",
  SJC: "San Jose",
  SJO: "San José CR",
  SJU: "San Juan",
  SLC: "Salt Lake City",
  SMF: "Sacramento",
  STL: "St. Louis",
  TPA: "Tampa",
  YOW: "Ottawa",
  YUL: "Montréal",
  YVR: "Vancouver",
  YYC: "Calgary",
  YYZ: "Toronto",

  // South America
  BOG: "Bogotá",
  BSB: "Brasília",
  BUE: "Buenos Aires",
  EZE: "Buenos Aires Ezeiza",
  GIG: "Rio de Janeiro",
  GRU: "São Paulo",
  GYE: "Guayaquil",
  LIM: "Lima",
  LPB: "La Paz",
  MDE: "Medellín",
  MVD: "Montevideo",
  SCL: "Santiago",
  UIO: "Quito",
  VVI: "Santa Cruz",

  // Oceania
  ADL: "Adelaide",
  AKL: "Auckland",
  BNE: "Brisbane",
  CHC: "Christchurch",
  CNS: "Cairns",
  DRW: "Darwin",
  MEL: "Melbourne",
  NAN: "Nadi",
  NOU: "Nouméa",
  OOL: "Gold Coast",
  PER: "Perth",
  PPT: "Tahiti",
  SYD: "Sydney",
  WLG: "Wellington",

  // Caribbean & Islands
  AUA: "Aruba",
  BGI: "Barbados",
  CUR: "Curaçao",
  GCM: "Grand Cayman",
  NAS: "Nassau",
  SXM: "St. Maarten",
};

/**
 * Format an IATA code as "City (CODE)" or just "CODE" if unknown.
 */
export function formatAirportCity(iataCode: string): string {
  if (!iataCode) return "";
  const code = iataCode.toUpperCase().trim();
  const city = AIRPORT_CITY_MAP[code];
  return city ? `${city} (${code})` : code;
}

/**
 * Format an array of IATA stops into a route string.
 * e.g. ["ADD", "MLE"] → "Addis Ababa (ADD) → Malé (MLE)"
 * e.g. ["JFK", "IST", "DXB"] → "New York JFK (JFK) → Istanbul (IST) → Dubai (DXB)"
 */
export function formatRoute(stops: string[]): string {
  if (!stops || stops.length === 0) return "";
  return stops.map(formatAirportCity).join("  →  ");
}

/**
 * IATA airport code → airport authority info (company name + domain).
 * - `name`: Official airport authority / managing company name (for brand search)
 * - `domain`: Official website domain (for logo.dev image URL)
 * Logo.dev: https://img.logo.dev/{domain}?token={key}
 */
export interface AirportLogoInfo {
  name: string;
  domain: string;
}

export const AIRPORT_LOGO_MAP: Record<string, AirportLogoInfo> = {
  // ── Africa ──────────────────────────────────────────────────────────────
  ADD: { name: "Addis Ababa Bole International Airport", domain: "addisababaairport.com" },
  ALG: { name: "Algiers Houari Boumediene Airport", domain: "egsa-alger.dz" },
  ACC: { name: "Kotoka International Airport", domain: "gacl.com.gh" },
  ABJ: { name: "Félix-Houphouët-Boigny International Airport", domain: "aaboridjan.aero" },
  CAI: { name: "Cairo International Airport", domain: "cairo-airport.com" },
  CPT: { name: "Cape Town International Airport", domain: "airports.co.za" },
  CMN: { name: "Mohammed V International Airport", domain: "onda.ma" },
  DAR: { name: "Julius Nyerere International Airport", domain: "taa.go.tz" },
  DSS: { name: "Blaise Diagne International Airport", domain: "dakaraeroport.com" },
  DUR: { name: "King Shaka International Airport", domain: "airports.co.za" },
  EBB: { name: "Entebbe International Airport", domain: "caa.go.ug" },
  JNB: { name: "O.R. Tambo International Airport", domain: "airports.co.za" },
  KGL: { name: "Kigali International Airport", domain: "rwandairports.com" },
  LOS: { name: "Murtala Muhammed International Airport", domain: "faan.gov.ng" },
  LAD: { name: "Quatro de Fevereiro International Airport", domain: "" },
  MBA: { name: "Moi International Airport", domain: "kaa.go.ke" },
  MPM: { name: "Maputo International Airport", domain: "" },
  NBO: { name: "Jomo Kenyatta International Airport", domain: "kaa.go.ke" },
  RAK: { name: "Marrakech Menara Airport", domain: "onda.ma" },
  RUN: { name: "Roland Garros Airport", domain: "" },
  SSH: { name: "Sharm El Sheikh International Airport", domain: "" },
  TUN: { name: "Tunis-Carthage International Airport", domain: "" },
  WDH: { name: "Hosea Kutako International Airport", domain: "airports.com.na" },
  ZNZ: { name: "Abeid Amani Karume International Airport", domain: "" },

  // ── Asia ─────────────────────────────────────────────────────────────────
  AMD: { name: "Sardar Vallabhbhai Patel International Airport", domain: "ahmedabadairport.com" },
  AUH: { name: "Abu Dhabi International Airport", domain: "abudhabiairport.ae" },
  BAH: { name: "Bahrain International Airport", domain: "bahrainairport.bh" },
  BKK: { name: "Suvarnabhumi Airport", domain: "airportthai.co.th" },
  BLR: { name: "Kempegowda International Airport", domain: "bengaluruairport.com" },
  BOM: { name: "Chhatrapati Shivaji Maharaj International Airport", domain: "adaniairports.com" },
  CCU: { name: "Netaji Subhas Chandra Bose International Airport", domain: "aai.aero" },
  CEB: { name: "Mactan-Cebu International Airport", domain: "mactancebuairport.com" },
  CGK: { name: "Soekarno-Hatta International Airport", domain: "angkasapura2.co.id" },
  CKG: { name: "Chongqing Jiangbei International Airport", domain: "" },
  CMB: { name: "Bandaranaike International Airport", domain: "airport.lk" },
  CNX: { name: "Chiang Mai International Airport", domain: "airportthai.co.th" },
  CTS: { name: "New Chitose Airport", domain: "new-chitose-airport.jp" },
  CTU: { name: "Chengdu Shuangliu International Airport", domain: "" },
  DAD: { name: "Da Nang International Airport", domain: "" },
  DEL: { name: "Indira Gandhi International Airport", domain: "newdelhiairport.in" },
  DPS: { name: "Ngurah Rai International Airport", domain: "baliairport.com" },
  DOH: { name: "Hamad International Airport", domain: "dohahamadairport.com" },
  DXB: { name: "Dubai International Airport", domain: "dubaiairports.ae" },
  FUK: { name: "Fukuoka Airport", domain: "" },
  GAN: { name: "Gan International Airport", domain: "" },
  GOI: { name: "Goa International Airport Dabolim", domain: "aai.aero" },
  HAN: { name: "Noi Bai International Airport", domain: "" },
  HGH: { name: "Hangzhou Xiaoshan International Airport", domain: "" },
  HKG: { name: "Hong Kong International Airport", domain: "hongkongairport.com" },
  HKT: { name: "Phuket International Airport", domain: "airportthai.co.th" },
  HND: { name: "Tokyo Haneda Airport", domain: "haneda-airport.jp" },
  HYD: { name: "Rajiv Gandhi International Airport", domain: "hyderabad.aero" },
  ICN: { name: "Incheon International Airport", domain: "airport.kr" },
  ISB: { name: "Islamabad International Airport", domain: "islamabadairport.com.pk" },
  JED: { name: "King Abdulaziz International Airport", domain: "jed-airport.com" },
  KHI: { name: "Jinnah International Airport", domain: "" },
  KIX: { name: "Kansai International Airport", domain: "kansai-airport.or.jp" },
  KTM: { name: "Tribhuvan International Airport", domain: "" },
  KUL: { name: "Kuala Lumpur International Airport", domain: "malaysiaairports.com.my" },
  KWI: { name: "Kuwait International Airport", domain: "dgca.gov.kw" },
  LHE: { name: "Allama Iqbal International Airport", domain: "" },
  MAA: { name: "Chennai International Airport", domain: "chennaiairport.com" },
  MCT: { name: "Muscat International Airport", domain: "omanairports.co.om" },
  MFM: { name: "Macau International Airport", domain: "macau-airport.com" },
  MLE: { name: "Velana International Airport", domain: "macl.aero" },
  MNL: { name: "Ninoy Aquino International Airport", domain: "miaa.gov.ph" },
  NRT: { name: "Narita International Airport", domain: "narita-airport.jp" },
  PBH: { name: "Paro International Airport", domain: "" },
  PEK: { name: "Beijing Capital International Airport", domain: "bcia.com.cn" },
  PKX: { name: "Beijing Daxing International Airport", domain: "" },
  PNH: { name: "Phnom Penh International Airport", domain: "cambodia-airports.aero" },
  PVG: { name: "Shanghai Pudong International Airport", domain: "" },
  REP: { name: "Siem Reap International Airport", domain: "cambodia-airports.aero" },
  RGN: { name: "Yangon International Airport", domain: "" },
  RUH: { name: "King Khalid International Airport", domain: "riyadhairports.com" },
  SGN: { name: "Tan Son Nhat International Airport", domain: "" },
  SHA: { name: "Shanghai Hongqiao International Airport", domain: "" },
  SIN: { name: "Singapore Changi Airport", domain: "changiairport.com" },
  SZX: { name: "Shenzhen Bao'an International Airport", domain: "" },
  TLV: { name: "Ben Gurion Airport", domain: "iaa.gov.il" },
  TPE: { name: "Taiwan Taoyuan International Airport", domain: "taoyuan-airport.com" },
  ULN: { name: "Chinggis Khaan International Airport", domain: "" },
  VTE: { name: "Wattay International Airport", domain: "" },
  XIY: { name: "Xi'an Xianyang International Airport", domain: "" },

  // ── Europe ──────────────────────────────────────────────────────────────
  AMS: { name: "Amsterdam Airport Schiphol", domain: "schiphol.nl" },
  ARN: { name: "Stockholm Arlanda Airport", domain: "swedavia.se" },
  ATH: { name: "Athens International Airport", domain: "aia.gr" },
  BCN: { name: "Barcelona–El Prat Airport", domain: "aena.es" },
  BEG: { name: "Belgrade Nikola Tesla Airport", domain: "beg.aero" },
  BER: { name: "Berlin Brandenburg Airport", domain: "berlin-airport.de" },
  BRU: { name: "Brussels Airport", domain: "brusselsairport.be" },
  BTS: { name: "Bratislava Airport", domain: "bts.aero" },
  BUD: { name: "Budapest Ferenc Liszt International Airport", domain: "bud.hu" },
  CDG: { name: "Paris Charles de Gaulle Airport", domain: "parisaeroport.fr" },
  CIA: { name: "Rome Ciampino Airport", domain: "adr.it" },
  CPH: { name: "Copenhagen Airport", domain: "cph.dk" },
  DUB: { name: "Dublin Airport", domain: "dublinairport.com" },
  DUS: { name: "Düsseldorf Airport", domain: "dus.com" },
  EDI: { name: "Edinburgh Airport", domain: "edinburghairport.com" },
  EVN: { name: "Zvartnots International Airport", domain: "" },
  FCO: { name: "Rome Fiumicino Airport", domain: "adr.it" },
  FRA: { name: "Frankfurt Airport", domain: "frankfurt-airport.com" },
  GVA: { name: "Geneva Airport", domain: "gva.ch" },
  HAM: { name: "Hamburg Airport", domain: "hamburg-airport.de" },
  HEL: { name: "Helsinki-Vantaa Airport", domain: "finavia.fi" },
  IST: { name: "Istanbul Airport", domain: "igairport.com" },
  KBP: { name: "Boryspil International Airport", domain: "kbp.aero" },
  LCA: { name: "Larnaca International Airport", domain: "hermesairports.com" },
  LED: { name: "Pulkovo Airport", domain: "" },
  LGW: { name: "London Gatwick Airport", domain: "gatwickairport.com" },
  LHR: { name: "Heathrow Airport", domain: "heathrow.com" },
  LIS: { name: "Lisbon Humberto Delgado Airport", domain: "ana.pt" },
  LTN: { name: "London Luton Airport", domain: "london-luton.co.uk" },
  LUX: { name: "Luxembourg Airport", domain: "lux-airport.lu" },
  MAD: { name: "Adolfo Suárez Madrid–Barajas Airport", domain: "aena.es" },
  MAN: { name: "Manchester Airport", domain: "manchesterairport.co.uk" },
  MLA: { name: "Malta International Airport", domain: "maltairport.com" },
  MUC: { name: "Munich Airport", domain: "munich-airport.de" },
  MXP: { name: "Milan Malpensa Airport", domain: "milanomalpensa-airport.com" },
  NAP: { name: "Naples International Airport", domain: "aeroportodinapoli.it" },
  NCE: { name: "Nice Côte d'Azur Airport", domain: "nice.aeroport.fr" },
  OPO: { name: "Porto Airport", domain: "ana.pt" },
  ORY: { name: "Paris Orly Airport", domain: "parisaeroport.fr" },
  OSL: { name: "Oslo Gardermoen Airport", domain: "avinor.no" },
  OTP: { name: "Bucharest Henri Coandă International Airport", domain: "bucharestairports.ro" },
  PMI: { name: "Palma de Mallorca Airport", domain: "aena.es" },
  PRG: { name: "Václav Havel Airport Prague", domain: "prg.aero" },
  RIX: { name: "Riga International Airport", domain: "riga-airport.com" },
  SAW: { name: "Istanbul Sabiha Gökçen Airport", domain: "sabihagokcen.aero" },
  SOF: { name: "Sofia Airport", domain: "sofia-airport.bg" },
  STN: { name: "London Stansted Airport", domain: "stanstedairport.com" },
  SVO: { name: "Sheremetyevo International Airport", domain: "" },
  TBS: { name: "Tbilisi International Airport", domain: "tbilisiairport.com" },
  TLL: { name: "Tallinn Airport", domain: "tallinn-airport.ee" },
  VCE: { name: "Venice Marco Polo Airport", domain: "veneziaairport.it" },
  VIE: { name: "Vienna International Airport", domain: "viennaairport.com" },
  VNO: { name: "Vilnius Airport", domain: "vilnius-airport.lt" },
  WAW: { name: "Warsaw Chopin Airport", domain: "lotnisko-chopina.pl" },
  ZAG: { name: "Zagreb Franjo Tuđman Airport", domain: "zagreb-airport.hr" },
  ZRH: { name: "Zurich Airport", domain: "zurich-airport.com" },

  // ── North America ───────────────────────────────────────────────────────
  ATL: { name: "Hartsfield-Jackson Atlanta International Airport", domain: "atl.com" },
  AUS: { name: "Austin-Bergstrom International Airport", domain: "austintexas.gov" },
  BNA: { name: "Nashville International Airport", domain: "flynashville.com" },
  BOS: { name: "Boston Logan International Airport", domain: "massport.com" },
  BWI: { name: "Baltimore/Washington International Airport", domain: "bwiairport.com" },
  CLE: { name: "Cleveland Hopkins International Airport", domain: "clevelandairport.com" },
  CLT: { name: "Charlotte Douglas International Airport", domain: "cltairport.com" },
  CUN: { name: "Cancún International Airport", domain: "asur.com.mx" },
  CVG: { name: "Cincinnati/Northern Kentucky International Airport", domain: "cvgairport.com" },
  DCA: { name: "Ronald Reagan Washington National Airport", domain: "flyreagan.com" },
  DEN: { name: "Denver International Airport", domain: "flydenver.com" },
  DFW: { name: "Dallas/Fort Worth International Airport", domain: "dfwairport.com" },
  DTW: { name: "Detroit Metropolitan Wayne County Airport", domain: "metroairport.com" },
  EWR: { name: "Newark Liberty International Airport", domain: "newarkairport.com" },
  FLL: { name: "Fort Lauderdale-Hollywood International Airport", domain: "broward.org" },
  GDL: { name: "Guadalajara International Airport", domain: "aeropuertogdl.com" },
  HAV: { name: "José Martí International Airport", domain: "" },
  HNL: { name: "Daniel K. Inouye International Airport", domain: "fly-hnl.com" },
  IAD: { name: "Washington Dulles International Airport", domain: "flydulles.com" },
  IAH: { name: "George Bush Intercontinental Airport", domain: "fly2houston.com" },
  IND: { name: "Indianapolis International Airport", domain: "ind.com" },
  JFK: { name: "John F. Kennedy International Airport", domain: "jfkairport.com" },
  KIN: { name: "Norman Manley International Airport", domain: "" },
  LAS: { name: "Harry Reid International Airport", domain: "harryreidairport.com" },
  LAX: { name: "Los Angeles International Airport", domain: "flylax.com" },
  LGA: { name: "LaGuardia Airport", domain: "laguardiaairport.com" },
  MBJ: { name: "Sangster International Airport", domain: "mbjairport.com" },
  MCI: { name: "Kansas City International Airport", domain: "flykci.com" },
  MCO: { name: "Orlando International Airport", domain: "orlandoairports.net" },
  MEX: { name: "Mexico City International Airport", domain: "aicm.com.mx" },
  MIA: { name: "Miami International Airport", domain: "miami-airport.com" },
  MKE: { name: "Milwaukee Mitchell International Airport", domain: "mitchellairport.com" },
  MSP: { name: "Minneapolis-Saint Paul International Airport", domain: "mspairport.com" },
  MSY: { name: "Louis Armstrong New Orleans International Airport", domain: "flymsy.com" },
  MTY: { name: "Monterrey International Airport", domain: "oma.aero" },
  OAK: { name: "Oakland International Airport", domain: "oaklandairport.com" },
  ORD: { name: "O'Hare International Airport", domain: "flychicago.com" },
  PBI: { name: "Palm Beach International Airport", domain: "pbia.org" },
  PDX: { name: "Portland International Airport", domain: "flypdx.com" },
  PHL: { name: "Philadelphia International Airport", domain: "phl.org" },
  PHX: { name: "Phoenix Sky Harbor International Airport", domain: "skyharbor.com" },
  PIT: { name: "Pittsburgh International Airport", domain: "flypittsburgh.com" },
  POS: { name: "Piarco International Airport", domain: "" },
  PTY: { name: "Tocumen International Airport", domain: "tocumenpanama.aero" },
  PUJ: { name: "Punta Cana International Airport", domain: "puntacanainternationalairport.com" },
  PVR: { name: "Licenciado Gustavo Díaz Ordaz International Airport", domain: "" },
  RDU: { name: "Raleigh-Durham International Airport", domain: "rdu.com" },
  RSW: { name: "Southwest Florida International Airport", domain: "flylcpa.com" },
  SAN: { name: "San Diego International Airport", domain: "san.org" },
  SAT: { name: "San Antonio International Airport", domain: "flysanantonio.com" },
  SEA: { name: "Seattle-Tacoma International Airport", domain: "portseattle.org" },
  SFO: { name: "San Francisco International Airport", domain: "flysfo.com" },
  SJC: { name: "San José Mineta International Airport", domain: "flysanjose.com" },
  SJO: { name: "Juan Santamaría International Airport", domain: "" },
  SJU: { name: "Luis Muñoz Marín International Airport", domain: "sanjuanairport.com" },
  SLC: { name: "Salt Lake City International Airport", domain: "slcairport.com" },
  SMF: { name: "Sacramento International Airport", domain: "sacramento.aero" },
  STL: { name: "St. Louis Lambert International Airport", domain: "flystl.com" },
  TPA: { name: "Tampa International Airport", domain: "tampaairport.com" },
  YOW: { name: "Ottawa Macdonald-Cartier International Airport", domain: "yow.ca" },
  YUL: { name: "Montréal-Trudeau International Airport", domain: "admtl.com" },
  YVR: { name: "Vancouver International Airport", domain: "yvr.ca" },
  YYC: { name: "Calgary International Airport", domain: "yyc.com" },
  YYZ: { name: "Toronto Pearson International Airport", domain: "torontopearson.com" },

  // ── South America ───────────────────────────────────────────────────────
  BOG: { name: "El Dorado International Airport", domain: "eldorado.aero" },
  BSB: { name: "Brasília International Airport", domain: "bsb.aero" },
  BUE: { name: "Aeropuertos Argentina 2000", domain: "aa2000.com.ar" },
  EZE: { name: "Ministro Pistarini International Airport", domain: "aa2000.com.ar" },
  GIG: { name: "Rio de Janeiro-Galeão International Airport", domain: "riogaleao.com" },
  GRU: { name: "São Paulo-Guarulhos International Airport", domain: "gru.com.br" },
  GYE: { name: "José Joaquín de Olmedo International Airport", domain: "tagsa.aero" },
  LIM: { name: "Jorge Chávez International Airport", domain: "lima-airport.com" },
  LPB: { name: "El Alto International Airport", domain: "" },
  MDE: { name: "José María Córdova International Airport", domain: "aeropuertojosemariacordova.com" },
  MVD: { name: "Carrasco International Airport", domain: "aeropuertodecarrasco.com.uy" },
  SCL: { name: "Arturo Merino Benítez International Airport", domain: "nuevopudahuel.cl" },
  UIO: { name: "Mariscal Sucre International Airport", domain: "quiport.com" },
  VVI: { name: "Viru Viru International Airport", domain: "" },

  // ── Oceania ─────────────────────────────────────────────────────────────
  ADL: { name: "Adelaide Airport", domain: "adelaideairport.com.au" },
  AKL: { name: "Auckland Airport", domain: "aucklandairport.co.nz" },
  BNE: { name: "Brisbane Airport", domain: "bne.com.au" },
  CHC: { name: "Christchurch Airport", domain: "christchurchairport.co.nz" },
  CNS: { name: "Cairns Airport", domain: "cairnsairport.com.au" },
  DRW: { name: "Darwin International Airport", domain: "darwinairport.com.au" },
  MEL: { name: "Melbourne Airport", domain: "melbourneairport.com.au" },
  NAN: { name: "Nadi International Airport", domain: "airportsfiji.com" },
  NOU: { name: "La Tontouta International Airport", domain: "" },
  OOL: { name: "Gold Coast Airport", domain: "goldcoastairport.com.au" },
  PER: { name: "Perth Airport", domain: "perthairport.com.au" },
  PPT: { name: "Faa'a International Airport", domain: "" },
  SYD: { name: "Sydney Kingsford Smith Airport", domain: "sydneyairport.com.au" },
  WLG: { name: "Wellington Airport", domain: "wellingtonairport.co.nz" },

  // ── Caribbean & Islands ─────────────────────────────────────────────────
  AUA: { name: "Queen Beatrix International Airport", domain: "airportaruba.com" },
  BGI: { name: "Grantley Adams International Airport", domain: "grantleyadamsairport.com" },
  CUR: { name: "Curaçao International Airport", domain: "curacao-airport.com" },
  GCM: { name: "Owen Roberts International Airport", domain: "caymanairports.com" },
  NAS: { name: "Lynden Pindling International Airport", domain: "nassaulpia.com" },
  SXM: { name: "Princess Juliana International Airport", domain: "sxmairport.com" },
};

const LOGO_DEV_TOKEN =
  (process.env.REACT_APP_LOGO_DEV_KEY as string) || "pk_LB4WaWyUTY2D1ABo9Hg_pg";

/**
 * Build a logo.dev URL for a given airport domain.
 */
function logoDevUrl(domain: string): string {
  return `https://img.logo.dev/${domain}?token=${LOGO_DEV_TOKEN}&size=128&format=png`;
}

/**
 * Get the airport logo URL for a given IATA code via logo.dev.
 * Returns undefined if the code is unknown or has no domain mapped.
 */
export function getAirportLogo(iataCode: string): string | undefined {
  if (!iataCode) return undefined;
  const code = iataCode.toUpperCase().trim();
  const info = AIRPORT_LOGO_MAP[code];
  return info?.domain ? logoDevUrl(info.domain) : undefined;
}

/**
 * Get the airport authority/company name for a given IATA code.
 */
export function getAirportName(iataCode: string): string | undefined {
  if (!iataCode) return undefined;
  const code = iataCode.toUpperCase().trim();
  return AIRPORT_LOGO_MAP[code]?.name || undefined;
}

export default AIRPORT_CITY_MAP;
