// import { SeatPropertyAttributes } from "./types/types";

// const allSeats: (SeatPropertyAttributes | null)[][] = [
//   [
//     {
//       _id: "1A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: true,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "1B",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: true,
//       armTrayRight: true,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "1C",
//       status: "available",
//       unsuitableForHandicap: true,
//       armTrayLeft: true,
//       armTrayRight: true,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "1D",
//       status: "unavailable",
//       unsuitableForHandicap: true,
//       armTrayLeft: true,
//       armTrayRight: true,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "1E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: true,
//       armTrayRight: true,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "1F",
//       status: "vip",
//       unsuitableForHandicap: false,
//       armTrayLeft: true,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "2A",
//       status: "vip",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "2B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "2C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: true,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "2D",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "2E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "2F",
//       status: "vip",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "3A",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "3B",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "3C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: true,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "3D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "3E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "3F",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "4A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "4B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "4C",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "4D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "4E",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "4F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "5A",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "5B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "5C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "5D",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "5E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "5F",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "6A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "6B",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "6C",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "6D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "6E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "6F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "7A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "7B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "7C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "7D",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "7E",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "7F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "8A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "8B",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "8C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "8D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "8E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "8F",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "9A",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "9B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "9C",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "9D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "9E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "9F",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "10A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "10B",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "10C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "10D",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "10E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "10F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "11A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "11B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "11C",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "11D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "11E",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "11F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "12A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: true,
//     },
//     {
//       _id: "12B",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: true,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "12C",
//       status: "available",
//       unsuitableForHandicap: true,
//       armTrayLeft: false,
//       armTrayRight: true,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "12D",
//       status: "available",
//       unsuitableForHandicap: true,
//       armTrayLeft: true,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "12E",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: true,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "12F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: true,
//     },
//   ],
//   [
//     {
//       _id: "13A",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: true,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "13B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: true,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "13C",
//       status: "available",
//       unsuitableForHandicap: true,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "13D",
//       status: "occupied",
//       unsuitableForHandicap: true,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "13E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: true,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "13F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: true,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: true,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "14A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "14B",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "14C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "14D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "14E",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "14F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "15A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "15B",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "15C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "15D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "15E",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "15F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "16A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "16B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "16C",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "16D",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "16E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "16F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "17A",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "17B",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "17C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "17D",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "17E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "17F",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "18A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "18B",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "18C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "18D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "18E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "18F",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "19A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "19B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "19C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "19D",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "19E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "19F",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "20A",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "20B",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "20C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "20D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "20E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "20F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "21A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "21B",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "21C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "21D",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "21E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "21F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "22A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "22B",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "22C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "22D",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "22E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "22F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "23A",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "23B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "23C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: true,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "23D",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "23E",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "23F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "24A",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "24B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "24C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: true,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "24D",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "24E",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//     {
//       _id: "24F",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: false,
//       hideSeat: false,
//     },
//   ],
//   [
//     {
//       _id: "25A",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "25B",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "25C",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: true,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     null,
//     {
//       _id: "25D",
//       status: "unavailable",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "25E",
//       status: "occupied",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//     {
//       _id: "25F",
//       status: "available",
//       unsuitableForHandicap: false,
//       armTrayLeft: false,
//       armTrayRight: false,
//       babyHammock: false,
//       handicapArmRest: false,
//       noBreakOver: false,
//       limitedRecline: false,
//       noRecline: true,
//       hideSeat: false,
//     },
//   ],
// ];

// export default allSeats;
